name: incoxpense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.6
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/auth/
    - assets/logo/
    - assets/menu/
    - assets/user/
