// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLs1QZVqD4C0dl1vWan6Pl4RdeQjpBG5o',
    appId: '1:844893913067:android:5129a0fab13a2b67c7a3ae',
    messagingSenderId: '844893913067',
    projectId: 'incoxpense-a3a80',
    storageBucket: 'incoxpense-a3a80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvjR_bNf33A6UfCP1wskYOCd57siaEJo',
    appId: '1:844893913067:ios:44c8d39b1bc21170c7a3ae',
    messagingSenderId: '844893913067',
    projectId: 'incoxpense-a3a80',
    storageBucket: 'incoxpense-a3a80.appspot.com',
    androidClientId: '844893913067-4818lhg66nkj1kjnhr8kapepvab54904.apps.googleusercontent.com',
    iosClientId: '844893913067-pdcnsdc0e8950itag23tegjuueo8384g.apps.googleusercontent.com',
    iosBundleId: 'com.example.incoxpense',
  );

}